#!/usr/bin/env bash
set -euo pipefail

# install nix
if ! command -v nix &>/dev/null; then
  echo "\033[94mInstalling Nix...\033[0m"
  curl -fsSL https://install.determinate.systems/nix | sh -s -- install --no-confirm
fi

# make nix available to current script
if [ ! -n "${NIX_PROFILES:-}" ]; then
  . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi

# use local nixpkgs
if [ -z "${NIXPKGS:-}" ]; then
  echo "\033[94mInstalling canonical nixpkgs...\033[0m"
  if ! NIXPKGS=$(nix eval --raw --impure \
    --expr 'let flake = builtins.getFlake "github:marksisson/parts"; in flake.inputs.nixpkgs.outPath'
  ); then echo "Failed to fetch nixpkgs (GitHub rate limit?)" >&2; exit 1
  fi
  export NIXPKGS
fi

# add local nixpkgs to user registry
nix registry add nixpkgs $NIXPKGS

# install packages needed by remainder of script
if [ -z "${SCRIPT_IN_NIX_SHELL:-}" ]; then
  export SCRIPT_IN_NIX_SHELL=1
  exec nix shell nixpkgs#bash nixpkgs#gawk nixpkgs#git nixpkgs#gnupg nixpkgs#jq --command bash "$@"
fi

pretty_print() {
  local completion="${1:-}"  # optional completion message
  if [[ -z "$PRETTY_PRINT" ]]; then
    PRETTY_PRINT=$(curl -fsSL https://raw.githubusercontent.com/marksisson/bootstrap/main/pretty-print) || {
      echo "Failed to fetch pretty-print" >&2; return 1
    }
  fi
  gawk -v completion="$completion" "$PRETTY_PRINT"
}

echo

# semantic tags for pretty printing
export HEADER="HEADER" STEP="STEP"
export CHOICE="CHOICE" DONE="DONE"
export SUCCESS="SUCCESS" WARNING="WARNING" ERROR="ERROR"

# install gnupg configuration
export GNUPGHOME="$HOME/.config/gnupg"
if [ ! -f "$GNUPGHOME/gpg-agent.conf" ]; then
  echo $STEP "Retrieving gnupg configuration..." | pretty_print
  nix run github:marksisson/gnupg |& pretty_print
fi

# enable ssh auth via gpg-agent
if [[ "${SSH_AUTH_SOCK:-}" != *gpg-agent* ]]; then
  echo $STEP "Configuring ssh..." | pretty_print
  export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
  mkdir -p "$HOME/.ssh" && ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
fi

echo

[ "$(uname -s)" = "Darwin" ] && {
  # install darwin configuration
  if ! command -v darwin-rebuild &>/dev/null; then
    # move files that nix-darwin will overwrite
    if [ -f /etc/nix/nix.custom.conf ]; then
      sudo mv /etc/nix/nix.custom.conf /etc/nix/nix.custom.conf.before-nix-darwin
    fi
    if [ -f /etc/zshenv ]; then
      sudo mv /etc/zshenv /etc/zshenv.before-nix-darwin
    fi

    echo $STEP "Retrieving darwin configurations..." | pretty_print
    DARWIN_CONFIGS=$(nix eval --json --impure --expr \
      'let flake = builtins.getFlake "git+ssh://git@github.com/marksisson/configurations"; in builtins.attrNames flake.outputs.darwinConfigurations' \
      2> >(pretty_print " " >&2) | jq -r '.[]' | grep -v '^default$')

    # convert newline-separated list to an array
    mapfile -t DARWIN_CONFIGS_ARRAY <<< "$DARWIN_CONFIGS"

    echo $CHOICE "Select darwin configuration:" | pretty_print
    select DARWIN_CONFIG in "${DARWIN_CONFIGS_ARRAY[@]}"; do
      [[ -n $DARWIN_CONFIG ]] && break
      echo $WARNING "Invalid selection, try again." | pretty_print
    done < /dev/tty

    echo

    sudo nix run --override-input nixpkgs $(nix registry resolve nixpkgs) github:nix-darwin/nix-darwin#darwin-rebuild -- \
      switch --flake git+ssh://git@github.com/marksisson/configurations#${DARWIN_CONFIG} |& pretty_print "$SUCCESS Darwin configuration complete..."
  fi

  # restart nix daemon to pickup nix configuration changes
  sudo launchctl kickstart -k system/systems.determinate.nix-daemon
}

[ "$(uname -s)" = "Linux" ] && {
  echo $STEP "Retrieving nixos configurations..." | pretty_print
  NIXOS_CONFIGS=$(nix eval --json --impure --expr \
    'let flake = builtins.getFlake "git+ssh://git@github.com/marksisson/configurations"; in builtins.attrNames flake.outputs.nixosConfigurations' \
    2> >(pretty_print " " >&2) | jq -r '.[]' | grep -v '^default$')

  # convert newline-separated list to an array
  mapfile -t NIXOS_CONFIGS_ARRAY <<< "$NIXOS_CONFIGS"

  echo $CHOICE "Select nixos configuration:" | pretty_print
  select NIXOS_CONFIG in "${NIXOS_CONFIGS_ARRAY[@]}"; do
    [[ -n $NIXOS_CONFIG ]] && break
    echo $WARNING "Invalid selection, try again." | pretty_print
  done < /dev/tty
  
  # install nixos configuration
  echo $ERROR "NixOS install not yet implemented"
  exit 1
}

# install home-manager configuration
if ! command -v home-manager &>/dev/null; then
  echo $STEP "Retrieving home configurations..." | pretty_print
  HOME_CONFIGS=$(nix eval --json --impure --expr \
    'let flake = builtins.getFlake "git+ssh://git@github.com/marksisson/configurations"; in builtins.attrNames flake.outputs.homeConfigurations' \
    2> >(pretty_print " " >&2) | jq -r '.[]' | grep -v '^default$')

  # convert newline-separated list to an array
  mapfile -t HOME_CONFIGS_ARRAY <<< "$HOME_CONFIGS"

  echo $CHOICE "Select home configuration:" | pretty_print
  select HOME_CONFIG in "${HOME_CONFIGS_ARRAY[@]}"; do
    [[ -n $HOME_CONFIG ]] && break
    echo $WARNING "Invalid selection, try again." | pretty_print
  done < /dev/tty

  echo

  export NIXPKGS_ALLOW_UNFREE=1 NIXPKGS_ALLOW_BROKEN=1
  nix run --override-input nixpkgs $(nix registry resolve nixpkgs) github:nix-community/home-manager#home-manager -- \
    switch -b backup --flake git+ssh://git@github.com/marksisson/configurations#${HOME_CONFIG} --impure |& pretty_print "$SUCCESS Home configuration complete..."
fi

# remove local nixpkgs from user registry
nix registry remove nixpkgs

echo $DONE "Done!" | pretty_print
