#!/usr/bin/env bash
set -euo pipefail

# prompt for sudo upfront
if ! sudo -n true 2>/dev/null; then
  printf "\033[92mRequesting sudo access...\n\033[0m"
  sudo -v < /dev/tty || { echo "Failed to get sudo access. Exiting."; exit 1; }
fi

# Keep sudo alive in background (refresh every 60s)
(while true; do sudo -n true; sleep 60; done) & SUDO_KEEPALIVE_PID=$!

# Make sure to kill the background process on exit
cleanup() { kill "$SUDO_KEEPALIVE_PID" 2>/dev/null || true; }
trap cleanup EXIT INT TERM

# install nix
if ! command -v nix &>/dev/null; then
  printf "\033[94mInstalling Nix...\n\033[0m"
  curl -fsSL https://install.determinate.systems/nix | sh -s -- install --no-confirm
fi

# make nix available to current script
if [ ! -n "${NIX_PROFILES:-}" ]; then
  . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi

# use local nixpkgs
if [ -z "${NIXPKGS:-}" ]; then
  printf "\033[94mInstalling canonical nixpkgs...\n\033[0m"
  if ! NIXPKGS=$(nix eval --raw --impure \
    --expr 'let flake = builtins.getFlake "github:marksisson/parts"; in flake.inputs.nixpkgs.outPath'
  ); then echo "Failed to fetch nixpkgs (GitHub rate limit?)" >&2; exit 1
  fi
  export NIXPKGS
fi

# add local nixpkgs to user registry
nix registry add nixpkgs $NIXPKGS

# install packages needed by remainder of script
if [ -z "${SCRIPT_IN_NIX_SHELL:-}" ]; then
  export SCRIPT_IN_NIX_SHELL=1
  cleanup # since script is not exiting (just exec'ing), manually cleanup sudo keepalive
  exec nix shell nixpkgs#bash nixpkgs#gawk nixpkgs#git nixpkgs#gnupg nixpkgs#jq --command bash "$@"
fi

# nb. this function will not parse with default (old) macos bash; need bash from nixpkgs
# nb. using gawk (from nixpkgs) for advanced match function
pretty_print() {
  local completion="${1:-}"  # optional completion message

  if [[ -z "$PRETTY_PRINT" ]]; then
    PRETTY_PRINT=$(curl -fsSL https://raw.githubusercontent.com/marksisson/bootstrap/main/pretty-print) || {
      echo "Failed to fetch pretty-print" >&2; return 1
    }
  fi

  gawk -v completion="$completion" "$PRETTY_PRINT"
}

echo

# install gnupg configuration
export GNUPGHOME="$HOME/.config/gnupg"
if [ ! -f "$GNUPGHOME/gpg-agent.conf" ]; then
  printf "Installing gnupg configuration...\n" | pretty_print
  nix run github:marksisson/gnupg 2>&1 | pretty_print
fi

# enable ssh auth via gpg-agent
if [[ "${SSH_AUTH_SOCK:-}" != *gpg-agent* ]]; then
  printf "Configuring ssh...\n" | pretty_print
  export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

  # add github ssh host keys
  mkdir -p "$HOME/.ssh"
  ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
fi

echo

[ "$(uname -s)" = "Darwin" ] && {
  # install darwin configuration
  if ! command -v darwin-rebuild &>/dev/null; then
    # move files that nix-darwin will overwrite
    if [ -f /etc/nix/nix.custom.conf ]; then
      sudo mv /etc/nix/nix.custom.conf /etc/nix/nix.custom.conf.before-nix-darwin
    fi
    if [ -f /etc/zshenv ]; then
      sudo mv /etc/zshenv /etc/zshenv.before-nix-darwin
    fi

    printf "Retrieving darwin configurations...\n" | pretty_print
    DARWIN_CONFIGS=$(nix eval --json --impure --expr \
      'let flake = builtins.getFlake "git+ssh://git@github.com/marksisson/configurations"; in builtins.attrNames flake.outputs.darwinConfigurations' 2> >(pretty_print -v completion=" " >&2) \
      | jq -r '.[]' | grep -v '^default$')

    # convert newline-separated list to an array
    mapfile -t DARWIN_CONFIGS_ARRAY <<< "$DARWIN_CONFIGS"

    printf "Select darwin configuration:\n" | pretty_print
    select DARWIN_CONFIG in "${DARWIN_CONFIGS_ARRAY[@]}"; do
      [[ -n $DARWIN_CONFIG ]] && break
      printf "Invalid selection, try again.\n" | pretty_print
    done < /dev/tty

    echo
    sudo nix run --override-input nixpkgs $(nix registry resolve nixpkgs) github:nix-darwin/nix-darwin#darwin-rebuild -- \
      switch --flake git+ssh://git@github.com/marksisson/configurations#${DARWIN_CONFIG} 2>&1 | pretty_print "Darwin configuration complete..."
    echo
  fi

  # restart nix daemon to pickup nix configuration changes
  sudo launchctl kickstart -k system/systems.determinate.nix-daemon
}

[ "$(uname -s)" = "Linux" ] && {
  printf "Retrieving nixos configurations...\n" | pretty_print
  NIXOS_CONFIGS=$(nix eval --json --impure --expr \
    'let flake = builtins.getFlake "git+ssh://git@github.com/marksisson/configurations"; in builtins.attrNames flake.outputs.nixosConfigurations' 2> >(pretty_print -v completion=" " >&2) \
    | jq -r '.[]' | grep -v '^default$')

  # convert newline-separated list to an array
  mapfile -t NIXOS_CONFIGS_ARRAY <<< "$NIXOS_CONFIGS"

  printf "Select nixos configuration:\n" | pretty_print
  select NIXOS_CONFIG in "${NIXOS_CONFIGS_ARRAY[@]}"; do
    [[ -n $NIXOS_CONFIG ]] && break
    printf "Invalid selection, try again.\n" | pretty_print
  done < /dev/tty
  
  # install nixos configuration
  echo "NixOS install not yet implemented"
  exit 1
}

# install home-manager configuration
if ! command -v home-manager &>/dev/null; then
  printf "Retrieving home configurations...\n" | pretty_print
  HOME_CONFIGS=$(nix eval --json --impure --expr \
    'let flake = builtins.getFlake "git+ssh://git@github.com/marksisson/configurations"; in builtins.attrNames flake.outputs.homeConfigurations' 2> >(pretty_print -v completion=" " >&2) \
    | jq -r '.[]' | grep -v '^default$')

  # convert newline-separated list to an array
  mapfile -t HOME_CONFIGS_ARRAY <<< "$HOME_CONFIGS"

  printf "Select home configuration:\n" | pretty_print
  select HOME_CONFIG in "${HOME_CONFIGS_ARRAY[@]}"; do
    [[ -n $HOME_CONFIG ]] && break
    printf "Invalid selection, try again.\n" | pretty_print
  done < /dev/tty

  echo
  export NIXPKGS_ALLOW_UNFREE=1 NIXPKGS_ALLOW_BROKEN=1
  nix run --override-input nixpkgs $(nix registry resolve nixpkgs) github:nix-community/home-manager#home-manager -- \
    switch -b backup --flake git+ssh://git@github.com/marksisson/configurations#${HOME_CONFIG} --impure 2>&1 | pretty_print "Home configuration complete..."
  echo
fi

# remove local nixpkgs from user registry
nix registry remove nixpkgs

printf "Done!\n" | pretty_print
